import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Shelf from "src/components/shelf";
import Blog from "src/components/blog";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [offset, setOffset] = useState(0);

  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="./assets/logo.png" className={styles.mainlogo}></img>
        <Shelf offset={offset}></Shelf>
        {/* A button property for loading the next of items */}
        <div className={styles.prevnext}>
          <button
            className={styles.nav}
            // onClick={() => setOffset((offset) => offset - 10)}
          >
            PREV
          </button>
          <button
            className={styles.nav}
            // onClick={() => setOffset((offset) => offset + 10)}
          >
            NEXT
          </button>
        </div>
      </main>
      <Blog></Blog>
    </>
  );
}
