import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Shelf from "src/components/shelf";
import Blog from "src/components/blog";
import React, { useEffect, useState } from "react";

export default function Home() {
  const [offset, setOffset] = useState(0);

  function incrementOffset() {
    if (offset < 1279) setOffset((offset) => offset + 10);
  }
  function decrementOffset() {
    if (offset > 0) setOffset((offset) => offset - 10);
  }

  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="./assets/logo.png" className={styles.mainlogo}></img>
        <Shelf offset={offset}></Shelf>
        {/* A button property for loading the next of items */}
        <div className={styles.prevnext}>
          <button
            className={offset === 0 ? styles.navdisabled : styles.nav}
            onClick={() => decrementOffset()}
          >
            PREV
          </button>
          <button
            className={offset > 1200 ? styles.navdisabled : styles.nav}
            onClick={() => incrementOffset()}
          >
            NEXT
          </button>
        </div>
      </main>
      <Blog></Blog>
    </>
  );
}
