import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Shelf from "src/components/shelf";
import Blog from "src/components/blog";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="./assets/logo.png" className={styles.mainlogo}></img>
        <Shelf></Shelf>
        {/* A button property for loading the next of items */}
        <div className={styles.prevnext}>
          <button></button>
          <button></button>
        </div>
      </main>

      <Blog></Blog>
    </>
  );
}
